version: '3.4'

services:
  uow.api:
    image: ${DOCKER_REGISTRY-}uow
    container_name: mongo-uow-api
    build:
      context: .
      dockerfile: UOW.API/Dockerfile
    networks:
      - dotnetcorepromgrafana

  mongodb:
    container_name: mongo-uow
    image: mongo
    container_name: mongo
    hostname: "mongodb"
    networks:
      - dotnetcorepromgrafana

  prometheus:
    image: prom/prometheus:0.18.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - dotnetcorepromgrafana
    
  grafana: 
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Password@1
    restart: always
    ports:
      - 3000:3000
    networks:
      - dotnetcorepromgrafana

networks:
  dotnetcorepromgrafana:
